// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Purple_Kutphane_Sistemi.Data;

#nullable disable

namespace Purple_Kutphane_Sistemi.Migrations
{
    [DbContext(typeof(DbBaglanti))]
    [Migration("20240822104912_addReferences")]
    partial class addReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.HesapTalep", b =>
                {
                    b.Property<int>("talep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("talep_id"));

                    b.Property<int?>("SistemYoneticiKullanici_id")
                        .HasColumnType("integer");

                    b.Property<int?>("YoneticiKullanici_id")
                        .HasColumnType("integer");

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gorevli_id")
                        .HasColumnType("integer");

                    b.Property<string>("son_onaylanma_tarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("talep_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasKey("talep_id");

                    b.HasIndex("SistemYoneticiKullanici_id");

                    b.HasIndex("YoneticiKullanici_id");

                    b.HasIndex("gorevli_id");

                    b.HasIndex("uye_id");

                    b.ToTable("HesapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KitapID"));

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<string>("KitapIsim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YayınEvi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("basimYili")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KitapID");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapAlim", b =>
                {
                    b.Property<int>("alis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("alis_id"));

                    b.Property<DateTime>("alis_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("kitap_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("teslim_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasKey("alis_id");

                    b.HasIndex("kitap_id");

                    b.HasIndex("uye_id");

                    b.ToTable("KitapAlimlari");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapTalep", b =>
                {
                    b.Property<int>("talep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("talep_id"));

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gorevli_id")
                        .HasColumnType("integer");

                    b.Property<int>("kitap_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("son_onaylanma_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("talep_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasKey("talep_id");

                    b.HasIndex("gorevli_id");

                    b.HasIndex("kitap_id");

                    b.HasIndex("uye_id");

                    b.ToTable("KitapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kullanici", b =>
                {
                    b.Property<int>("Kullanici_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Kullanici_id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayıtTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Kullanici_id");

                    b.ToTable("Kullanicilar", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yazar", b =>
                {
                    b.Property<int>("yazar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("yazar_id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayıtTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("yazar_id");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Gorevli", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int?>("Kullanici_id1")
                        .HasColumnType("integer");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("gorevli_id")
                        .HasColumnType("integer");

                    b.HasIndex("Kullanici_id1");

                    b.ToTable("Gorevliler", (string)null);
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.SistemYonetici", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int?>("Kullanici_id1")
                        .HasColumnType("integer");

                    b.Property<int>("sys_admin_id")
                        .HasColumnType("integer");

                    b.HasIndex("Kullanici_id1");

                    b.ToTable("SistemYoneticileri", (string)null);
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Uye", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int?>("Kullanici_id1")
                        .HasColumnType("integer");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasIndex("Kullanici_id1");

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yonetici", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int?>("Kullanici_id1")
                        .HasColumnType("integer");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("yonetici_id")
                        .HasColumnType("integer");

                    b.HasIndex("Kullanici_id1");

                    b.ToTable("Yonetici", (string)null);
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.HesapTalep", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.SistemYonetici", null)
                        .WithMany("HesapTalepleri")
                        .HasForeignKey("SistemYoneticiKullanici_id");

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Yonetici", null)
                        .WithMany("HesapTalepleri")
                        .HasForeignKey("YoneticiKullanici_id");

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Gorevli", "Gorevli")
                        .WithMany("HesapTalepleri")
                        .HasForeignKey("gorevli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Uye", "uye")
                        .WithMany("HesapTalepleri")
                        .HasForeignKey("uye_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorevli");

                    b.Navigation("uye");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapAlim", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kitap", "Kitap")
                        .WithMany("KitapAlimlari")
                        .HasForeignKey("kitap_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Uye", "uye")
                        .WithMany("KitapAlimlari")
                        .HasForeignKey("uye_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("uye");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapTalep", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Gorevli", "Gorevli")
                        .WithMany("KitapTalepleri")
                        .HasForeignKey("gorevli_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kitap", "Kitap")
                        .WithMany("KitapTalepleri")
                        .HasForeignKey("kitap_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Uye", "uye")
                        .WithMany("KitapTalepleri")
                        .HasForeignKey("uye_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorevli");

                    b.Navigation("Kitap");

                    b.Navigation("uye");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Gorevli", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithOne()
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Gorevli", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithMany("Gorevliler")
                        .HasForeignKey("Kullanici_id1");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.SistemYonetici", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithOne()
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.SistemYonetici", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithMany("SistemYoneticileri")
                        .HasForeignKey("Kullanici_id1");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Uye", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithOne()
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Uye", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithMany("Uyeler")
                        .HasForeignKey("Kullanici_id1");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yonetici", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithOne()
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Yonetici", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", null)
                        .WithMany("Yoneticiler")
                        .HasForeignKey("Kullanici_id1");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kitap", b =>
                {
                    b.Navigation("KitapAlimlari");

                    b.Navigation("KitapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kullanici", b =>
                {
                    b.Navigation("Gorevliler");

                    b.Navigation("SistemYoneticileri");

                    b.Navigation("Uyeler");

                    b.Navigation("Yoneticiler");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Gorevli", b =>
                {
                    b.Navigation("HesapTalepleri");

                    b.Navigation("KitapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.SistemYonetici", b =>
                {
                    b.Navigation("HesapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Uye", b =>
                {
                    b.Navigation("HesapTalepleri");

                    b.Navigation("KitapAlimlari");

                    b.Navigation("KitapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yonetici", b =>
                {
                    b.Navigation("HesapTalepleri");
                });
#pragma warning restore 612, 618
        }
    }
}
