// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Purple_Kutphane_Sistemi.Data;

#nullable disable

namespace Purple_Kutphane_Sistemi.Migrations
{
    [DbContext(typeof(DbBaglanti))]
    [Migration("20240820132611_AddKullaniciReferences")]
    partial class AddKullaniciReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.HesapTalep", b =>
                {
                    b.Property<int>("talep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("talep_id"));

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("görevli_id")
                        .HasColumnType("integer");

                    b.Property<string>("kullanici_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("son_onaylanma_tarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("talep_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("talep_id");

                    b.ToTable("HesapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KitapID"));

                    b.Property<bool>("Durum")
                        .HasColumnType("boolean");

                    b.Property<string>("KitapIsim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YayınEvi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("basimYili")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KitapID");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapAlim", b =>
                {
                    b.Property<int>("alis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("alis_id"));

                    b.Property<DateTime>("alis_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("kitap_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("teslim_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasKey("alis_id");

                    b.ToTable("KitapAlimlari");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.KitapTalep", b =>
                {
                    b.Property<int>("talep_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("talep_id"));

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gorevli_id")
                        .HasColumnType("integer");

                    b.Property<int>("kitap_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("son_onaylanma_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("talep_tarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.HasKey("talep_id");

                    b.ToTable("KitapTalepleri");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kullanici", b =>
                {
                    b.Property<int>("Kullanici_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Kullanici_id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayıtTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Kullanici_id");

                    b.ToTable("Kullanicilar");

                    b.HasDiscriminator().HasValue("Kullanici");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yazar", b =>
                {
                    b.Property<int>("yazar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("yazar_id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayıtTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("yazar_id");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Gorevli", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int?>("KullaniciTempId")
                        .HasColumnType("integer");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("gorevli_id")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Gorevli");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.SistemYonetici", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<int>("sys_admin_id")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("SistemYonetici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Uye", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("uye_id")
                        .HasColumnType("integer");

                    b.ToTable("Kullanicilar", t =>
                        {
                            t.Property("ceza_durumu")
                                .HasColumnName("Uye_ceza_durumu");

                            t.Property("ceza_puani")
                                .HasColumnName("Uye_ceza_puani");
                        });

                    b.HasDiscriminator().HasValue("Uye");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yonetici", b =>
                {
                    b.HasBaseType("Purple_Kutphane_Sistemi.Data.Kullanici");

                    b.Property<bool>("ceza_durumu")
                        .HasColumnType("boolean");

                    b.Property<int>("ceza_puani")
                        .HasColumnType("integer");

                    b.Property<int>("yonetici_id")
                        .HasColumnType("integer");

                    b.ToTable("Kullanicilar", t =>
                        {
                            t.Property("ceza_durumu")
                                .HasColumnName("Yonetici_ceza_durumu");

                            t.Property("ceza_puani")
                                .HasColumnName("Yonetici_ceza_puani");
                        });

                    b.HasDiscriminator().HasValue("Yonetici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Gorevli", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", "Kullanici")
                        .WithOne("Gorevli")
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Gorevli", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.SistemYonetici", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", "Kullanici")
                        .WithOne("SistemYoneticisi")
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.SistemYonetici", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Uye", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", "Kullanici")
                        .WithOne("Uye")
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Uye", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Yonetici", b =>
                {
                    b.HasOne("Purple_Kutphane_Sistemi.Data.Kullanici", "Kullanici")
                        .WithOne("Yonetici")
                        .HasForeignKey("Purple_Kutphane_Sistemi.Data.Yonetici", "Kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Purple_Kutphane_Sistemi.Data.Kullanici", b =>
                {
                    b.Navigation("Gorevli")
                        .IsRequired();

                    b.Navigation("SistemYoneticisi")
                        .IsRequired();

                    b.Navigation("Uye")
                        .IsRequired();

                    b.Navigation("Yonetici")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
